### ISSUE TITLE
Dependencies problem with Rails 4.2.0

### ISSUE THREAD

**Issue by yuya4** [msevestre/monologue_image_upload#6]
I faced an issue I couldn't bundle install the monologue_image_upload gem.

I'm using Rails 4.2.0 and at first simply tried to bundle the gem,
 Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    monologue_image_upload (>= 0) ruby depends on
      rails (< 4.2.0, >= 4.0.0) ruby
    rails (4.2.0)

Next tried to bundle the gem with rails 4.1.5 and issued bundle update rails

 Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    jquery-rails (>= 0) ruby depends on
      railties (>= 4.2.0) ruby

  rails (= 4.1.5) ruby depends on
  railties (4.1.5)

jquery-rails seems depending on railities >= 4.2.0, but Rails 4.2.0 can't be used with this gem, right ?
Sorry for asking this if it's elementary question, please advise me if you know something.
Thanks.

**Comment by msevestre** [comment]
not now. PR welcome :)

**Comment by Stormcore** [comment]
There is pull request, can you merge please?

**Comment by katawura** [comment]
Is there any way you can update this files please @msevestre  l keep getting this error:
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (= 4.0.4) ruby depends on
      railties (= 4.0.4) ruby

    monologue_image_upload (>= 0) ruby depends on
      monologue (>= 0) ruby depends on
        responders (~> 2.1.0) ruby depends on
          railties (< 5, >= 4.2.0) ruby

**Comment by msevestre** [comment]
ok let's try again . That should be fixed now

**Comment by katawura** [comment]
Tht seems fixed thanks @msevestre  . One last question, is there anyway to pull in only the image in your post? l am having a look in irb and l get this: 

irb(main):011:0> Monologue::Post.find_by_id(2)
  Monologue::Post Load (0.2ms)  SELECT  "monologue_posts".* FROM "monologue_posts" WHERE "monologue_posts"."id" = ? LIMIT 1  [["id", 2]]
  Monologue::Tagging Load (0.1ms)  SELECT "monologue_taggings".* FROM "monologue_taggings" WHERE "monologue_taggings"."post_id" IN (2)
=> #<Monologue::Post id: 2, published: true, created_at: "2015-11-27 14:00:16", updated_at: "2015-11-27 14:00:16", user_id: 1, title: "Image test", content: "<p><img alt=\"\" src=\"/monologue/pictures/2/content_...", url: "image-test", published_at: "2015-11-27 00:00:00">

Thus l can only pull in the image with the content and not the image on its own.

**Comment by LvcasX1** [comment]
Hi! i've trying to install this gem but it throws thie error: 

Retrying git clone 'git@github.com:msevestre/monologue_image_upload.git' "/Users/lvcasx1/.rvm/gems/ruby-2.2.0/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:msevestre/monologue_image_upload.git' "/Users/lvcasx1/.rvm/gems/ruby-2.2.0/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet` in directory /Users/lvcasx1/Nnodes/nnodes_web has failed.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by msevestre** [comment]
You should probably fork the repo and then clone it
To use the gem however you should update your gemfile
Hope that helps

**Comment by Bw00d** [comment]
Sounds like I am having the same problem as LvcasX1. I added: 

gem "monologue_image_upload", :git => "git@github.com:msevestre/monologue_image_upload.git"

to my gemfile and when I run 'bundle' I get this error:

Fetching git@github.com:msevestre/monologue_image_upload.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone 'git@github.com:msevestre/monologue_image_upload.git' "/Users/bwood/.rvm/gems/ruby-2.1.5/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet due to error (2/3): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:msevestre/monologue_image_upload.git' "/Users/bwood/.rvm/gems/ruby-2.1.5/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet` in directory /Users/bwood/code/rails/4.2/fire-faces has failed.
Permission denied (publickey).
fatal: Could not read from remote repository.

I am using rails 4.2.0

Do you have any idea what might be the issue?

**Comment by InsomniaNoir** [comment]
I have a similar issue when I try to push to heroku:

remote:        Host key verification failed.
remote:        fatal: Could not read from remote repository.
remote:
remote:        Please make sure you have the correct access rights
remote:        and the repository exists.
remote:        Retrying git clone 'git@github.com:msevestre/monologue_image_upload.git' "/tmp/build_a95ca50548ae6c60f65dac614f4c2f40/vendor/bundle/ruby/2.2.0/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:msevestre/monologue_image_upload.git' "/tmp/build_a95ca50548ae6c60f65dac614f4c2f40/vendor/bundle/ruby/2.2.0/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet` in directory /tmp/build_a95ca50548ae6c60f65dac614f4c2f40 has failed.
remote:        Host key verification failed.
remote:        fatal: Could not read from remote repository.
remote:
remote:        Please make sure you have the correct access rights
remote:        and the repository exists.
remote:        Git error: command `git clone
remote:        'git@github.com:msevestre/monologue_image_upload.git'
remote:        "/tmp/build_a95ca50548ae6c60f65dac614f4c2f40/vendor/bundle/ruby/2.2.0/cache/bundler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9"
remote:        --bare --no-hardlinks --quiet` in directory
remote:        /tmp/build_a95ca50548ae6c60f65dac614f4c2f40 has failed.

**Comment by jipiboily** [comment]
I see no reason for that at first...this is a public repo...but you can do as
Michael suggested: Fork the repo and use your fork...?  
  

Jean-Philippe Boily  

  

**PS**: Want to get the most out of Google Analytics? [Get our free email course](http://metricswatch.com/free-5-part-email-course/).  

  

Founder @ **Metrics Watch** | [metricswatch.com](http://metricswatch.com/) -
**Spend less time** watching your Google Analytics metrics. You will be
alerted in near real-time when there is something worth looking at!**  
**

**  
**

**Also consultant helping B2B SaaS to improve their conversion rates and revenues.**  

  
![](https://link.nylas.com/open/1amhcpc54qheo68giuxk2opf/local-0ebc4428-4b40)

On May 8 2016, at 10:32 pm, Jeremiah Shafer &lt;notifications@github.com&gt;
wrote:  

> I have a similar issue when I try to push to heroku:

>

> remote: Host key verification failed.  
remote: fatal: Could not read from remote repository.  
remote:  
remote: Please make sure you have the correct access rights  
remote: and the repository exists.  
remote: Retrying git clone
'[git@github.com](mailto:git@github.com):msevestre/monologue_image_upload.git'
"/tmp/build_a95ca50548ae6c60f65dac614f4c2f40/vendor/bundle/ruby/2.2.0/cache/bu
ndler/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9"
--bare --no-hardlinks --quiet due to error (4/4):
Bundler::Source::Git::GitCommandError Git error: command `git clone
'git@github.com:msevestre/monologue_image_upload.git' "/tmp/build_a95ca50548ae
6c60f65dac614f4c2f40/vendor/bundle/ruby/2.2.0/cache/bundler/git
/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-
hardlinks --quiet` in directory /tmp/build_a95ca50548ae6c60f65dac614f4c2f40
has failed.  
remote: Host key verification failed.  
remote: fatal: Could not read from remote repository.  
remote:  
remote: Please make sure you have the correct access rights  
remote: and the repository exists.  
remote: Git error: command `git clone  
remote: 'git@github.com:msevestre/monologue_image_upload.git'  
remote: "/tmp/build_a95ca50548ae6c60f65dac614f4c2f40/vendor/bundle/ruby/2.2.0/
cache/bundler/git/monologue_image_upload-
34d6c03dbe659e9454eede0dabfb247af27e98c9"  
remote: --bare --no-hardlinks --quiet` in directory  
remote: /tmp/build_a95ca50548ae6c60f65dac614f4c2f40 has failed.

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/msevest
re/monologue_image_upload/issues/6#issuecomment-217764386)![](https://github.c
om/notifications/beacon/AAOOIYciGo-
7rkQzD5jpRnYoIpj133dvks5p_pzIgaJpZM4D3BDz.gif)

**Comment by InsomniaNoir** [comment]
I've tried this as well. I updated my gemfile to show:

```gem "monologue_image_upload", :git => "git@github.com:InsomniaNoir/monologue_image_upload.git"```

I still get the following error:

Host key verification failed.
remote:        fatal: Could not read from remote repository.
remote:
remote:        Please make sure you have the correct access rights
remote:        and the repository exists.
remote:        Git error: command `git clone
remote:        'git@github.com:InsomniaNoir/monologue_image_upload.git'
remote:        "/tmp/build_96c0a207145b5ab208b835be4fec1624/vendor/bundle/ruby/2.3.0/cache/bundler/git/monologue_image_upload-9fd6088226068ae88052114776ec3b70d10b1f70"
remote:        --bare --no-hardlinks --quiet` in directory
remote:        /tmp/build_96c0a207145b5ab208b835be4fec1624 has failed.
remote:  !
remote:  !     Failed to install gems via Bundler.

**Comment by jipiboily** [comment]
It looks like the same kind error you would get with Heroku if your SSH key is
problematic or something. I don't think this is specific to this project. I
would reach out to Heroku's support to be honest.  
  

Jean-Philippe Boily  

  

**PS**: Want to get the most out of Google Analytics? [Get our free email course](http://metricswatch.com/free-5-part-email-course/).  

  

Founder @ **Metrics Watch** | [metricswatch.com](http://metricswatch.com/) -
**Spend less time** watching your Google Analytics metrics. You will be
alerted in real-time when there is something worth looking at!**  
**

**  
**

**Also consultant helping B2B SaaS to improve their conversion rates and revenues.**  

  
![](https://link.nylas.com/open/1amhcpc54qheo68giuxk2opf/local-8e95ed13-9e8d)

On May 9 2016, at 2:19 pm, Jeremiah Shafer &lt;notifications@github.com&gt;
wrote:  

> I've tried this as well. I updated my gemfile to show:

>

> `gem "monologue_image_upload", :git =>
"git@github.com:InsomniaNoir/monologue_image_upload.git"`

>

> I still get the following error:

>

> Host key verification failed.  
remote: fatal: Could not read from remote repository.  
remote:  
remote: Please make sure you have the correct access rights  
remote: and the repository exists.  
remote: Git error: command `git clone  
remote: 'git@github.com:InsomniaNoir/monologue_image_upload.git'  
remote: "/tmp/build_96c0a207145b5ab208b835be4fec1624/vendor/bundle/ruby/2.3.0/
cache/bundler/git/monologue_image_upload-
9fd6088226068ae88052114776ec3b70d10b1f70"  
remote: --bare --no-hardlinks --quiet` in directory  
remote: /tmp/build_96c0a207145b5ab208b835be4fec1624 has failed.  
remote: !  
remote: ! Failed to install gems via Bundler.

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/msevest
re/monologue_image_upload/issues/6#issuecomment-217945624)![](https://github.c
om/notifications/beacon/AAOOIeXnYi1eIxieplIohKmuWjwzYot8ks5p_3rLgaJpZM4D3BDz.g
if)

**Comment by ewarman** [comment]
Hi all... I solved this issue by cloning the https interface. Add this to your gemfile instead:
```ruby
gem 'monologue_image_upload', :git => "https://github.com/msevestre/monologue_image_upload.git"
```

**Comment by msevestre** [comment]
Nicely done. Can you update the readme with a PR?

**Comment by msevestre** [comment]
I guess I can do it myself lol. Thanks a lot
